apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo2
spec:
  replicas: 1
  selector:
    app: mongo2
  template:
    metadata:
      name: mongo2
      labels:
        app: mongo2
    spec:
      containers:
      - name: mongo2
        image: mongo:3.4
        args:
        - --nojournal
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
