apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: designer
  name: designer
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 32663
  - name: "1030"
    port: 1030
    targetPort: 1030
    nodePort: 31803
  selector:
    io.kompose.service: designer
status:
  loadBalancer: {}
