#cloud-config
# vim: syntax=yaml
---
openstack:
  vm_name_prefix: yadav
  key_name: yadav2 
  flavor: m1.large
  private_network: demo-net
  external_network: ext-net
  image: centos7.5
  security_groups: sandbox_kube
  key_path: /home/necuser/Desktop/yadav2.pem
  count: 3
kubernetes:
  flannel_cidr: 10.244.0.0/16
