#cloud-config
# vim: syntax=yaml
---
openstack:
  vm_name_prefix: yadav
  key_name: yadav2
  flavor: m1.medium
  private_network: demo-net
  external_network: ext-net
  image: centos7.5     #supported Images versiona Centos7/ Ubuntu16 (name as your openstack image name)
  security_groups: sandbox_kube
  key_path: /root/yadav/yadav.pem
  count: 3

kubernetes:
  enable_kubernetes: "no"
  flannel_cidr: 10.244.0.0/16

enable_IotGEs: "no"

enable_orion: "no"
enable_sth_comet: "no"
enable_cygnus_sth: "no"
enable_cepheus: "no"
enable_cygnus_ckan: "no"
enable_ckan: "no"
enable_fogflow: "no"

NGB:
  enable_ngb: "no"
  vm_name_prefix: NGB
  key_name: yadav2
  flavor: m1.medium
  private_network: demo-net
  external_network: ext-net
  image: ubuntu_18.04
  security_groups: sandbox_kube
  key_path: /root/yadav/yadav.pem
  count: 1