---
- name: include_vars
  hosts: localhost
  tasks:
    - name: include_vars
      include_vars:
        file: cloud-config.yaml
        name: stuff
      changed_when: True

- name: create  kubernetes vms on openstack wtih floating ips using cloud-config.yaml
  gather_facts: true
  hosts: localhost
  roles:
    - role: vm-deploy
      when:
        - stuff.kubernetes.enable_kubernetes  | bool

- name: Apply ngb-vm-deploy
  gather_facts: true
  #become: True
  hosts:
    - localhost
  roles:
    - role: ngb-vm-deploy
      when:
        - stuff.NGB.enable_ngb  | bool

- name: include_vars
  hosts: all
  tasks:
    - name: include_vars
      include_vars:
        file: cloud-config.yaml
        name: stuff
      changed_when: True

- name: Apply  kubernetes-common role for common tasks
  gather_facts: true
  become: True
  hosts:
    - kubernetes
  roles:
    - role: kubernetes-common
      when:
        - stuff.kubernetes.enable_kubernetes  | bool
#      when: kolla_action == "precheck"

- name: Apply kubernetes master role for kubernetes master tasks
  gather_facts: true
  become: True
  hosts:
    - master
  roles:
    - role: master
      when:
        - stuff.kubernetes.enable_kubernetes  | bool

- name: Apply kubernetes worker role for kubernetes worker tasks
  gather_facts: true
  become: True
  hosts:
    - worker
  roles:
    - role: worker
      when:
        - stuff.openstack.count > 1
        - stuff.kubernetes.enable_kubernetes  | bool

- name: Apply kubernetes-post-deploy role for kubernetes post deploy check
  gather_facts: true
  become: True
  hosts:
    - master
  roles:
    - role: kubernetes-post-deploy

- name: install IoTGEs
  gather_facts: true
  become: True
  hosts:
    - master
  roles:
    - role: IotGEs
      when:
        - stuff.enable_IotGEs  | bool

- name: Apply ngb deploy
  gather_facts: true
  #become: True
  hosts:
    - NGB
  roles:
    - role: NGB
      when:
        - stuff.NGB.enable_ngb  | bool
#- name: Destroy VM on OpenStack
#  hosts: localhost
#  gather_facts: false
#  roles:
#    - role: vm-destroy
