apiVersion: v1
kind: Service
metadata:
  name: mongo-client
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0
#    role: mongo
