---
#- include_vars:
#    file: cloud-config.yaml
#    name: stuff

- name: Grant centos user passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: 'centos ALL=(ALL) NOPASSWD: ALL'
  become: yes
  become_method: "sudo"

- name: Install libselinux to disable selinux
  yum:
    pkg=libselinux-python
    state=present

- name: Disable selinux
  selinux: state=disabled

- name: disable SELinux
  command: setenforce 0
  ignore_errors: True

- name: "Install python2 and python-simplejson"
  become: True
  raw: "yum install -y python python-simplejson || (apt-get update && apt-get install -y python2.7 python-simplejson)"

- name: Gather facts
  setup:

- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {% for host in groups['kubernetes'] %}
        {{ ansible_default_ipv4.address }} {{ hostvars[host]['ansible_hostname']+".novalocal " + hostvars[host]['ansible_hostname'] }}
        {% endfor %}
  become: True

- name: Copying kubernetes.repo file to dest nodes 
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: ensure a list of kubernetes packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - kubeadm
    - docker
    - vim-enhanced
    - wget

- name: Add the below entries in the conf file to change the Linux host bridge values.
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
  changed_when: True
  with_items:
    - "net.bridge.bridge-nf-call-iptables = 1"
    - "net.bridge.bridge-nf-call-ip6tables = 1"

- name: start and enable kubernetes services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - docker
    - kubelet