---
# tasks file
- name: copying ckan package directory to file with owner and permissions
  copy:
    src: ./IoTGEs-templates/ckan
    dest: /tmp/IotGEs/
    owner: root
    group: root
    mode: 0777

- name:  run nfs-server on kubernetes master
  shell: ./nfs-master.sh
  args:
    chdir: /tmp/IotGEs/ckan
  changed_when: True

- name: copying prodution.ini file with owner and permissions
  copy:
    src: ./IoTGEs-templates/ckan/production.ini
    dest: /ckan/ckanconfig/production.ini
    owner: root
    group: root
    mode: 0777

- name: copying who.ini file with owner and permissions
  copy:
    src: ./IoTGEs-templates/ckan/who.ini
    dest: /ckan/ckanconfig/who.ini
    owner: root
    group: root
    mode: 0777

- name: copying perm.sh file with owner and permissions
  copy:
    src: ./IoTGEs-templates/ckan/perm.sh
    dest: /ckan/db/perm.sh
    owner: root
    group: root
    mode: 0777

- name: copying perm1.sh file with owner and permissions
  copy:
    src: ./IoTGEs-templates/ckan/perm1.sh
    dest: /ckan/db/perm1.sh
    owner: root
    group: root
    mode: 0777

- name:  run /tmp/dbperm.sh shell script to set db permissions
  command: sed -i  's,ckan.site_url = http://localhost:5000,ckan.site_url = http://{{groups['master'][0]}}:5000,g' /ckan/ckanconfig/production.ini
  register: siteurl_change_output

- name: add nfs server ip to ckan pv1
  lineinfile:
    path: /tmp/IotGEs/ckan/volume1.yaml
    insertafter: '  nfs:'
    line: '    server: {{ ansible_default_ipv4.address }}'

- name: add nfs server ip to ckan pv2
  lineinfile:
    path: /tmp/IotGEs/ckan/volume2.yaml
    insertafter: '  nfs:'
    line: '    server: {{ ansible_default_ipv4.address }}'

- name: add nfs server ip to ckan pv3
  lineinfile:
    path: /tmp/IotGEs/ckan/volume3.yaml
    insertafter: '  nfs:'
    line: '    server: {{ ansible_default_ipv4.address }}'

- name: add IP of master to externalIPs in ckan service template
  lineinfile:
    path: /tmp/IotGEs/ckan/ckan-service.yaml
    insertafter: 'externalIPs:'
    line: '  - {{master_internal_ip}}'


- name:  in ckan service template
  lineinfile:
    path: /tmp/IotGEs/ckan/ckan-service.yaml
    insertafter: '- name: CKAN_SITE_URL'
    line: '          value: http://{{master_internal_ip}}:5000'

- name: find db pods
  command: kubectl get pods --selector=io.kompose.service=db
  register: dbpodname_before
  ignore_errors: yes

- name:  install ckan GE
  shell: ./ckan_one_click.sh
  args:
    chdir: /tmp/IotGEs/ckan
  changed_when: False
  when: "'Running' not in dbpodname_before "

- name: find db pods
  command: kubectl get pods --selector=io.kompose.service=db
  register: dbpodname

- set_fact:
            db_pod_name: "{{ dbpodname.stdout_lines[1].split(' ')[0] }}"

- name: find ckan pods
  command: kubectl get pods --selector=io.kompose.service=ckan
  register: ckanpodname

- set_fact:
            ckan_pod_name: "{{ ckanpodname.stdout_lines[1].split(' ')[0] }}"

- name: create /tmp/dbperm.sh file
  file:
    path: /tmp/dbperm.sh
    state: touch
    mode: 0755

- name: add db permissions commands and ckan useradd commands to dbperm.sh file.
  blockinfile:
    path: /tmp/dbperm.sh
    content: |
      kubectl exec -it {{ db_pod_name }} bash --tty=false  <<'EOF'
      /opt/perm1.sh
      EOF
      kubectl exec -it {{ ckan_pod_name }} bash --tty=false  <<'EOF'
      /usr/local/bin/ckan-paster --plugin=ckan user add yadav apikey=4f884745-99a9-4389-954e-43513903f39b password=abc@1234 email=ravinder.kumar@india.nec.com  --config=/etc/ckan/production.ini
      /usr/local/bin/ckan-paster --plugin=ckan sysadmin add yadav   --config=/etc/ckan/production.ini
      EOF

- name:  run /tmp/dbperm.sh shell script to set db permissions
  command: /tmp/dbperm.sh
  register: dbperm2
  ignore_errors: yes

- debug:
    msg: "ckan is running on     http://{{groups['master'][0]}}:5000            "
