---
# tasks file
- name: copying fogflow installer directory to file with owner and permissions
  copy:
    src: ./IoTGEs-templates/fogflow
    dest: /tmp/IotGEs/
    owner: root
    group: root
    mode: 0755

- name: copying fogflow config directory to file with owner and permissions
  copy:
    src: ./config/fogflow
    dest: /tmp/IotGEs/config
    owner: root
    group: root
    mode: 0755

- name: copying fogflow usecase directory to file with owner and permissions
  copy:
    src: ./fogflow_usecases
    dest: /root
    owner: root
    group: root
    mode: 0755


########################

- name: adding rabbitmq_ip in configuration file of broker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/broker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "rabbitmq_ip": "{{ inventory_hostname }}",'

- name: adding discovery_ip in configuration file of broker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/broker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "discovery_ip": "{{ inventory_hostname }}",'

- name: adding master_ip in configuration file of broker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/broker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "master_ip": "{{ inventory_hostname }}",'

- name: adding broker_ip in configuration file of broker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/broker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "broker_ip": "{{ inventory_hostname }}",'

#######################

- name: adding rabbitmq_ip in configuration file of designer
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/designer/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "rabbitmq_ip": "{{ inventory_hostname }}",'

- name: adding discovery_ip in configuration file of designer
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/designer/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "discovery_ip": "{{ inventory_hostname }}",'

- name: adding broker_ip in configuration file of designer
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/designer/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "broker_ip": "{{ inventory_hostname }}",'

- name: adding agent_ip in configuration file of designer
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/designer/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "agent_ip": "{{ inventory_hostname }}",'

- name: adding master_ip in configuration file of designer
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/designer/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "master_ip": "{{ inventory_hostname }}",'


#######################

- name: adding rabbitmq_ip in configuration file of master
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/master/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "rabbitmq_ip": "{{ inventory_hostname }}",'

- name: adding discovery_ip in configuration file of master
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/master/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "discovery_ip": "{{ inventory_hostname }}",'

- name: adding broker_ip in configuration file of master
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/master/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "broker_ip": "{{ inventory_hostname }}",'

- name: adding master_ip in configuration file of master
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/master/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "master_ip": "{{ inventory_hostname }}",'

#######################

- name: adding rabbitmq_ip in configuration file of cloud-worker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/cloud-worker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "rabbitmq_ip": "{{ inventory_hostname }}",'

- name: adding discovery_ip in configuration file of cloud-worker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/cloud-worker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "discovery_ip": "{{ inventory_hostname }}",'

- name: adding broker_ip in configuration file of cloud-worker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/cloud-worker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "broker_ip": "{{ inventory_hostname }}",'

- name: adding master_ip in configuration file of cloud-worker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/cloud-worker/config.json
    insertbefore: '    "discovery_port": 32073,'
    line: '    "master_ip": "{{ inventory_hostname }}",'

- name: adding discovery.postgresql.host in configuration file of cloud-worker
  lineinfile:
    path: /tmp/IotGEs/config/fogflow/cloud-worker/config.json
    insertbefore: '            "port": 5432,'
    line: '            "host": "{{ inventory_hostname }}",'

##################

- name: add IP of master to externalIPs of rabbitmq service
  lineinfile:
    path: /tmp/IotGEs/fogflow/rabbitmq-service.yaml
    insertafter: 'externalIPs:'
    line: '  - {{master_internal_ip}}'

- name: add IP of master to externalIPs of postgis service
  lineinfile:
    path: /tmp/IotGEs/fogflow/postgis-service.yaml
    insertafter: 'externalIPs:'
    line: '  - {{master_internal_ip}}'

- name: add IP of master to externalIPs of discovery service
  lineinfile:
    path: /tmp/IotGEs/fogflow/discovery-service.yaml
    insertafter: 'externalIPs:'
    line: '  - {{master_internal_ip}}'

- name: add IP of master to externalIPs of broker service
  lineinfile:
    path: /tmp/IotGEs/fogflow/broker-service.yaml
    insertafter: 'externalIPs:'
    line: '  - {{master_internal_ip}}'

- name: add IP of master to externalIPs of designer service
  lineinfile:
    path: /tmp/IotGEs/fogflow/designer-service.yaml
    insertafter: 'externalIPs:'
    line: '  - {{master_internal_ip}}'

- name: add IP of master to externalIPs of master service
  lineinfile:
    path: /tmp/IotGEs/fogflow/master-service.yaml
    insertafter: 'externalIPs:'
    line: '  - {{master_internal_ip}}'

################

- name:  installing fogflow
  shell: ./fogflow_one_click.sh
  args:
    chdir: /tmp/IotGEs/fogflow
  changed_when: True

- name:  displaying fogflow access information
  debug:
    msg: "Fogflow has been deployed Successfully. Access the portal at {{ inventory_hostname }}:32663"
