apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: datapusher
    spec:
      containers:
      - image: clementmouchet/datapusher
        name: datapusher
        ports:
        - containerPort: 8800
        resources: {}
      restartPolicy: Always
status: {}
