apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: datapusher
  name: ckandatapusher
spec:
  ports:
  - name: "8800"
    port: 8800
    targetPort: 8800
  selector:
    io.kompose.service: datapusher
