apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: solr
    spec:
      containers:
      - image: rhcayadav/ckan_docker_solr:v1.1
        name: solr
        ports:
        - containerPort: 8983
        resources: {}
      restartPolicy: Always
status: {}
