apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckandbperm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: ckandbperm
  nfs:
    path: /ckan/db

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckandbperm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
