apiVersion: v1
kind: ReplicationController
metadata:
  name: orion
spec:
  replicas: 2 
  selector:
    app: orion
  template:
    metadata:
      name: orion
      labels:
        app: orion
    spec:
      containers:
      - name: orion
        image: fiware/orion
        args:
        - -dbhost
        - mongo-client.default.svc.cluster.local
        ports:
        - containerPort: 1026
        resources: {}
      restartPolicy: Always

