kind: Service
apiVersion: v1
metadata:
  name: orion
spec:
  type: NodePort
  ports:
  - name: "1026"
    port: 1028
    targetPort: 1026
    nodePort: 32101
  selector:
    app: orion
status:
  loadBalancer: {}
#  externalIPs:
#    - 195.134.187.35
#  ports:
#  - name: http
#    protocol: TCP
#    port: 1026
#    targetPort: 1026
