apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: orion
    app: orion
  name: orion
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orion
        app: orion
    spec:
      containers:
      - image: fiware/orion
        name: orion
        args:
        - -dbhost
        - mongo-client.default.svc.cluster.local
        ports:
        - containerPort: 1026
        resources: {}        
      restartPolicy: Always      
status: {}
