apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sth22
  name: fiware-sth-comet2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: sth22
    spec:
      containers:
      - env:
        - name: DB_URI
          value: mongo2.default.svc.cluster.local:27017
        - name: STH_HOST
          value: 0.0.0.0
        image: telefonicaiot/fiware-sth-comet
        name: fiware-sth-comet
        ports:
        - containerPort: 8666
        resources: {}
      restartPolicy: Always
status: {}
