- k8s_raw:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: mongo-pv0
      spec:
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Recycle
        nfs:
          path: /opt/data/vol/0
          server: {{ ansible_default_ipv4.address }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
- k8s_raw:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: mongo-pv1
      spec:
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Recycle
        nfs:
          path: /opt/data/vol/1
          server: {{ ansible_default_ipv4.address }}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
- k8s_raw:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: mongo-pv2
      spec:
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Recycle
        nfs:
          path: /opt/data/vol/2
          server: {{ ansible_default_ipv4.address }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
