- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: master
    ansible_ssh_user: centos
    ansible_become: True
    ansible_become_user: root
    ansible_private_key_file: "{{ stuff.AWS.key_path }}"
  loop: "{{ ec2_vms.instances[:1] }}"
  when:
    - stuff.AWS.count > 1
    - stuff.base_distro == 'centos'

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: kubernetes
    ansible_ssh_user: centos
    ansible_become: True
    ansible_become_user: root
    ansible_private_key_file: "{{ stuff.AWS.key_path }}"
  loop: "{{ ec2_vms.instances }}"
  when:
    - stuff.AWS.count > 1
    - stuff.base_distro == 'centos'

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: worker
    ansible_ssh_user: centos
    ansible_become: True
    ansible_become_user: root
    ansible_private_key_file: "{{ stuff.AWS.key_path }}"
  loop: "{{ ec2_vms.instances[1:] }}"
  when:
    - stuff.AWS.count > 1
    - stuff.base_distro == 'centos'

- name: if count is 1 than add that host to all groups
  add_host:
    hostname: "{{ item.public_ip }}"
    groups:
      - kubernetes
      - master
    ansible_ssh_user: centos
    ansible_become: True
    ansible_become_user: root
    ansible_private_key_file: "{{ stuff.AWS.key_path }}"
  loop: "{{ ec2_vms.instances }}"
  when:
    - stuff.AWS.count == 1
    - stuff.base_distro == 'centos'

