---
# tasks file for worker
- name: example copying file with owner and permissions
  copy:
    src: /tmp/mydata
    dest: /tmp/mydata
    owner: root
    group: root
    mode: 0755
  register: fatching_mydata_file

- name:  list kubernetes nodes
  command: kubectl get nodes
  register: before_existing_nodes1
  ignore_errors: yes

- name:  run kubeadm join to add workers in cluster
  command: "{{ user_data }}"
  register: kubejointoken1
  when: fatching_mydata_file.changed
  changed_when: False
  failed_when:
    - kubejointoken1.rc != 0
  when:
  - "{{groups['worker'][-1]}} not in before_existing_nodes1.stdout"

- debug:
    msg: "{{ kubejointoken1 }}"