---
# tasks file for worker
- name: example copying file with owner and permissions
  copy:
    src: /tmp/mydata
    dest: /tmp/mydata
    owner: root
    group: root
    mode: 0755
  register: fatching_mydata_file
  changed_when: False

- name:  run kubeadm join to add workers in cluster
  command: "{{ user_data }}"
  register: kubejointoken1
  changed_when: False
  failed_when:
    - kubejointoken1.rc != 0
  when:
  - ansible_hostname not in before_existing_nodes1.stdout

- debug:
    msg: "{{ kubejointoken1 }}"