apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo2
    app: mongo2
  name: mongo2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo2
        app: mongo2
    spec:
      containers:
      - image: mongo:3.4
        name: mongo2
        args:
        - --nojournal
        ports:
        - containerPort: 27017
      restartPolicy: Always

