apiVersion: v1
kind: ReplicationController
metadata:
  name: cepheus
spec:
  replicas: 2
  selector:
    app: cepheus
  template:
    metadata:
      name: cepheus
      labels:
        app: cepheus
    spec:
      containers:
      - name: cepheus
        image: orangeopensource/fiware-cepheus
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
      restartPolicy: Always

